

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from 'react';
import { Context } from "react";
import { createContext } from "vm";
import MyContext from "./components/myContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sharedValue = "this is a shard value"


export default function RootLayout({
  


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <MyContext.Provider value = {sharedValue}>

      
      <body className="min-h-full flex flex-col">{children}</body>
      </MyContext.Provider>
    </html>
  );
}
